version: "3.7"
services:
  eventbus:
    image: nats-streaming
    ports:
      - 4222:4222
      - 8222:8222
    command: [
      "-p", "4222",
      "-m", "8222",
      "-hbi", "5s",
      "-hbt", "5s",
      "-hbf", "2",
      "-SD",
      "-cid", "eventbus"
    ]
    networks:
      - backend
      - integration
  posts:
    build:
      context: .
      dockerfile: posts.dockerfile
    hostname: posts
    expose:
      - "4000"
    ports:
      - 4000:4000
    environment:
      - "NODE_ENV=production"
    depends_on:
      - eventbus
    networks:
      - backend
      - integration
  comments:
    build:
      context: .
      dockerfile: comments.dockerfile
    expose:
      - "4001"
    ports:
      - 4001:4001
    environment:
      - "NODE_ENV=production"
    depends_on:
      - eventbus
    networks:
      - backend
      - integration
  query:
    build:
      context: .
      dockerfile: query.dockerfile
    expose:
      - "4002"
    ports:
      - 4002:4002
    environment:
      - "NODE_ENV=production"
    depends_on:
      - eventbus
      - posts
      - comments
    networks:
      - backend
      - integration
  moderation:
    build:
      context: .
      dockerfile: moderation.dockerfile
    expose:
      - "4003"
    ports:
      - 4003:4003
    environment:
      - "NODE_ENV=production"
    depends_on:
      - eventbus
    networks:
      - backend
      - integration
  blogapp:
    build:
      context: .
      dockerfile: blogapp.dockerfile
    ports:
      - 3000:80
    environment:
      - "NODE_ENV=production"
    depends_on:
      - query
      - eventbus
    networks:
      - frontend
      - integration
  # eventbus:
  #   image: rabbitmq:3-management
  #   ports:
  #     - 7075:15672
  #     - 5672:5672
  #     - 25676:25676
networks:
  backend:
  frontend:
  integration: